# Generated by Django 5.2.5 on 2025-09-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='showed',
            new_name='shows',
        ),
    ]
