# Generated by Django 5.2.5 on 2025-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0002_rename_showed_quote_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
